import { Cinema } from './models/Cinema';

export const CINEMA: Cinema[] = [
  {
    id: 1,
    showId: 'tt1298644',
    maxSeatsInRow: 11,
    rows: 5,
    roomName: 'Room 1',
    room: [
      {
        rowLabel: 'A',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 1,
            positionRow: 0,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 2,
            positionRow: 0,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 3,
            positionRow: 0,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 4,
            positionRow: 0,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 5,
            positionRow: 0,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 999,
            seatNumber: 6,
            positionRow: 0,
            positionColumn: 8,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 101,
            seatNumber: 7,
            positionRow: 0,
            positionColumn: 9,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 102,
            seatNumber: 8,
            positionRow: 0,
            positionColumn: 10,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'B',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 1,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 1,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 1,
            positionColumn: 2,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 1,
            positionColumn: 3,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 1,
            positionColumn: 4,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 1,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 1,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 1,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 999,
            seatNumber: 8,
            positionRow: 0,
            positionColumn: 8,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 101,
            seatNumber: 9,
            positionRow: 0,
            positionColumn: 9,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 102,
            seatNumber: 10,
            positionRow: 0,
            positionColumn: 10,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'C',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 2,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 2,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 2,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 2,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 2,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 2,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 2,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 2,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 999,
            seatNumber: 8,
            positionRow: 0,
            positionColumn: 8,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 101,
            seatNumber: 9,
            positionRow: 0,
            positionColumn: 9,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 102,
            seatNumber: 10,
            positionRow: 0,
            positionColumn: 10,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'D',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 3,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 3,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 3,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 3,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 3,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 3,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 3,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 3,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 999,
            seatNumber: 8,
            positionRow: 0,
            positionColumn: 8,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 101,
            seatNumber: 9,
            positionRow: 0,
            positionColumn: 9,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 102,
            seatNumber: 10,
            positionRow: 0,
            positionColumn: 10,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'E',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 4,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 4,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 4,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 4,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 4,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 4,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 4,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 4,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 999,
            seatNumber: 8,
            positionRow: 0,
            positionColumn: 8,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 101,
            seatNumber: 9,
            positionRow: 0,
            positionColumn: 9,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 102,
            seatNumber: 10,
            positionRow: 0,
            positionColumn: 10,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
    ]
  },
  {
    id: 2,
    showId: 'tt7286456',
    maxSeatsInRow: 8,
    rows: 5,
    roomName: 'Room 2',
    room: [
      {
        rowLabel: 'A',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 1,
            positionRow: 0,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 2,
            positionRow: 0,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 3,
            positionRow: 0,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 4,
            positionRow: 0,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 5,
            positionRow: 0,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'B',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 1,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 1,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 1,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 1,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 1,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 1,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 1,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 1,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'C',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 2,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 2,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 2,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 2,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 2,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 2,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 2,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 2,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'D',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 3,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 3,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 3,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 3,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 3,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 3,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 3,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 3,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'E',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 4,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 4,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 4,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 4,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 4,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 4,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 4,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 4,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
    ]
  },
  {
    id: 3,
    showId: 'tt7343762',
    maxSeatsInRow: 8,
    rows: 5,
    roomName: 'Room 3',
    room: [
      {
        rowLabel: 'A',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 1,
            positionRow: 0,
            positionColumn: 2,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 2,
            positionRow: 0,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 3,
            positionRow: 0,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 0,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 4,
            positionRow: 0,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 5,
            positionRow: 0,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'B',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 1,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 1,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 1,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 1,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 1,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 1,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 1,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 1,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'C',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 2,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 2,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 2,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 2,
            positionColumn: 3,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 2,
            positionColumn: 4,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 2,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 2,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 2,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'D',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 3,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 3,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 3,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 3,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 3,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 3,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 3,
            positionColumn: 6,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 3,
            positionColumn: 7,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          }
        ]
      },
      {
        rowLabel: 'E',
        rowSeats: [
          {
            seatId: 111,
            seatNumber: 1,
            positionRow: 4,
            positionColumn: 0,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 222,
            seatNumber: 2,
            positionRow: 4,
            positionColumn: 1,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 333,
            seatNumber: 3,
            positionRow: 4,
            positionColumn: 2,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 444,
            seatNumber: 4,
            positionRow: 4,
            positionColumn: 3,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 555,
            seatNumber: 5,
            positionRow: 4,
            positionColumn: 4,
            price: 14.95,
            taken: false,
            available: true,
            selected: false,
          },
          {
            seatId: 666,
            seatNumber: -1,
            positionRow: 4,
            positionColumn: 5,
            price: 14.95,
            taken: false,
            available: false,
            selected: false,
          },
          {
            seatId: 777,
            seatNumber: 6,
            positionRow: 4,
            positionColumn: 6,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          },
          {
            seatId: 888,
            seatNumber: 7,
            positionRow: 4,
            positionColumn: 7,
            price: 14.95,
            taken: true,
            available: false,
            selected: false,
          }
        ]
      },
    ]
  },
]